---
title: "p8105_HW_2"
output: github_document
---

# Homework 2 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

## Problem 1
### Creating Dataframe for Mr. Trash Wheel Data
```{r}
trash_wheel_df <- 
  read_excel("./data_hw_2/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = "Mr. Trash Wheel") %>% 
  janitor::clean_names() %>% 
  select(-x15) %>% 
  drop_na(dumpster) %>% 
  mutate(
    sports_balls = round(pull(trash_wheel_df, sports_balls), 0) %>% 
      as.integer(pull(trash_wheel_df, sports_balls))
  )
```

### Creating Dataframe for 2018 Precipitation
```{r}
precip_2018 <- 
  read_excel("./data_hw_2/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = "2018 Precipitation", range = "A2:B14") %>% 
  drop_na(Total) %>% 
  mutate(
    year = 2018
  )
```

### Creating Dataframe for 2017 Precipitation
```{r}
precip_2017 <- 
  read_excel("./data_hw_2/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = "2017 Precipitation", range = "A2:B14") %>% 
  drop_na(Total) %>% 
  mutate(
    year = 2017
  )
```

### Combining 2017 and 2018 Precipitation Datasets
```{r}
precip_17_18 <- 
  bind_rows(precip_2017, precip_2018) %>% 
  janitor::clean_names() %>% 
  mutate(
    month = month.name[month]
  )
```

## Problem 2
### Tidying the dates 
### Need to figure out how to combine mutates
```{r}
pols_month_df <- 
  read_csv("./data_hw_2/fivethirtyeight_datasets/pols-month.csv") %>% 
  separate(mon, c("year", "month", "day")) %>%
  mutate(
    month = as.numeric(pull(., month)),
    month = month.name[month]
    )
```

### Create president variable
```{r}
pols_month_df <- 
  pivot_longer(
    pols_month_df,
    cols = c("prez_gop", "prez_dem"),
    names_to = "president",
    names_prefix = "prez_"
  ) %>% 
  mutate(value = na_if(value, 0)) %>% 
  drop_na() %>% 
  select(-c(value, day))
```

### Clean the data in snp 
```{r}
snp_df <- 
  read_csv("./data_hw_2/fivethirtyeight_datasets/snp.csv") %>% 
  separate(date, c("month", "day", "year")) %>% 
  mutate(
    month = as.numeric(pull(., month)),
    month = month.name[month]
    ) %>% 
  select(year, month, close, -day) %>% 
  arrange(year)
  
```

